REATE OR REPLACE PROCEDURE litify.update_litify_matter()
LANGUAGE plpgsql
AS $$
BEGIN

    CREATE TEMP TABLE temp_source_m AS 
    SELECT ms.* 
    FROM litify.matter_staging ms
    LEFT JOIN litify.matter m 
        ON ms.id = m.id
    WHERE m.id IS NULL OR ms.lastmodifieddate > m.lastmodifieddate;

    MERGE INTO litify.matter 
    USING temp_source_m AS source
    ON litify.matter.id = source.id

    WHEN MATCHED THEN UPDATE SET 
        ownerid = source.ownerid,
        isdeleted = source.isdeleted,
        name = source.name,
        recordtypeid = source.recordtypeid,
        createddate = source.createddate,
        createdbyid = source.createdbyid,
        lastmodifieddate = source.lastmodifieddate,
        lastmodifiedbyid = source.lastmodifiedbyid,
        systemmodstamp = source.systemmodstamp,
        lastactivitydate = source.lastactivitydate,
        litify_pm__billable_matter__c = source.litify_pm__billable_matter__c,
        litify_pm__billing_type__c = source.litify_pm__billing_type__c,
        litify_pm__case_type__c = source.litify_pm__case_type__c,
        litify_pm__client__c = source.litify_pm__client__c,
        litify_pm__closed_reason_details__c = source.litify_pm__closed_reason_details__c,
        litify_pm__closed_reason__c = source.litify_pm__closed_reason__c,
        litify_pm__description__c = source.litify_pm__description__c,
        litify_pm__display_name__c = source.litify_pm__display_name__c,
        litify_pm__ignore_default_plan__c = source.litify_pm__ignore_default_plan__c,
        litify_pm__limitations_date_satisfied__c = source.litify_pm__limitations_date_satisfied__c,
        litify_pm__matter_address_1__c = source.litify_pm__matter_address_1__c,
        litify_pm__matter_address_2__c = source.litify_pm__matter_address_2__c,
        litify_pm__matter_city__c = source.litify_pm__matter_city__c,
        litify_pm__matter_has_budget__c = source.litify_pm__matter_has_budget__c,
        litify_pm__matter_location__c = source.litify_pm__matter_location__c,
        litify_pm__matter_plan__c = source.litify_pm__matter_plan__c,
        litify_pm__matter_postal_code__c = source.litify_pm__matter_postal_code__c,
        litify_pm__matter_stage_activity_formula__c = source.litify_pm__matter_stage_activity_formula__c,
        litify_pm__matter_stage_activity__c = source.litify_pm__matter_stage_activity__c,
        litify_pm__matter_state__c = source.litify_pm__matter_state__c,
        litify_pm__matter__c = source.litify_pm__matter__c,
        litify_pm__open_date__c = source.litify_pm__open_date__c,
        litify_pm__originating_attorney__c = source.litify_pm__originating_attorney__c,
        litify_pm__primary_intake__c = source.litify_pm__primary_intake__c,
        litify_pm__principal_attorney__c = source.litify_pm__principal_attorney__c,
        litify_pm__source_type__c = source.litify_pm__source_type__c,
        litify_pm__source__c = source.litify_pm__source__c,
        litify_pm__status__c = source.litify_pm__status__c,
        litify_pm__total_amount_billable__c = source.litify_pm__total_amount_billable__c,
        litify_pm__total_amount_due__c = source.litify_pm__total_amount_due__c,
        litify_pm__total_matter_value__c = source.litify_pm__total_matter_value__c,
        litify_pm__total_matter_cost__c = source.litify_pm__total_matter_cost__c,
        litify_pm__use_same_client_location__c = source.litify_pm__use_same_client_location__c,
        litify_pm__total_amount_paid__c = source.litify_pm__total_amount_paid__c,
        litify_pm__total_amount_billed__c = source.litify_pm__total_amount_billed__c,
        litify_pm__total_amount_expensed_due__c = source.litify_pm__total_amount_expensed_due__c,
        litify_pm__total_amount_expensed__c = source.litify_pm__total_amount_expensed__c,
        litify_pm__total_amount_retained__c = source.litify_pm__total_amount_retained__c,
        litify_pm__total_amount_time_entries_billed__c = source.litify_pm__total_amount_time_entries_billed__c,
        litify_pm__total_amount_time_entries_due__c = source.litify_pm__total_amount_time_entries_due__c,
        litify_pm__total_amount_time_entries_unpaid__c = source.litify_pm__total_amount_time_entries_unpaid__c,
        litify_pm__total_amount_unbilled_expenses__c = source.litify_pm__total_amount_unbilled_expenses__c,
        litify_pm__total_hours__c = source.litify_pm__total_hours__c,
        litify_pm__total_amount_time_entries__c = source.litify_pm__total_amount_time_entries__c,
        litify_pm__last_called_at__c = source.litify_pm__last_called_at__c,
        litify_pm__last_emailed_at__c = source.litify_pm__last_emailed_at__c,
        litify_pm__total_calls__c = source.litify_pm__total_calls__c,
        litify_pm__total_emails__c = source.litify_pm__total_emails__c,
        litify_pm__closed_date__c = source.litify_pm__closed_date__c,
        litify_pm__default_matter_team__c = source.litify_pm__default_matter_team__c,
        litify_pm__matter_team_modified__c = source.litify_pm__matter_team_modified__c,
        litify_pm__filed_date__c = source.litify_pm__filed_date__c,
        litify_pm__total_damages__c = source.litify_pm__total_damages__c,
        litify_pm__lit_matter_county__c = source.litify_pm__lit_matter_county__c,
        litify_pm__lit_lien_total_currency__c = source.litify_pm__lit_lien_total_currency__c,
        internal_law_firm__c = source.internal_law_firm__c,
        litify_pm__manual_statute_of_limitations__c = source.litify_pm__manual_statute_of_limitations__c,
        litify_pm__lit_display_name_link__c = source.litify_pm__lit_display_name_link__c,
        case_type__c = source.case_type__c,
        litify_pm__lit_total_client_payout__c = source.litify_pm__lit_total_client_payout__c,
        litify_pm__lit_damage_total__c = source.litify_pm__lit_damage_total__c,
        litify_pm__lit_expense_total__c = source.litify_pm__lit_expense_total__c,
        litify_pm__lit_lien_total__c = source.litify_pm__lit_lien_total__c,
        cm_case_sub_type__c = source.cm_case_sub_type__c,
        run_triggers__c = source.run_triggers__c,
        litify_ext__isteammember__c = source.litify_ext__isteammember__c,
        litify_ext__mtm_ids__c = source.litify_ext__mtm_ids__c,
        litify_ext__private__c = source.litify_ext__private__c,
        isdeceased__c = source.isdeceased__c,
        open_date_text__c = source.open_date_text__c,
        serious_injury__c = source.serious_injury__c,
        isminor__c = source.isminor__c,
        conflict_check__c = source.conflict_check__c,
        conflict_check_notes__c = source.conflict_check_notes__c,
        office__c = source.office__c,
        billing_contact__c = source.billing_contact__c,
        payment_overdue__c = source.payment_overdue__c,
        case_updates__c = source.case_updates__c,
        client_info__c = source.client_info__c,
        case_number__c = source.case_number__c,
        legacy_id__c = source.legacy_id__c,
        data_migration_job_id__c = source.data_migration_job_id__c,
        total_billable_expenses__c = source.total_billable_expenses__c,
        total_unbilled_expenses__c = source.total_unbilled_expenses__c,
        total_billable_te__c = source.total_billable_te__c,
        total_unbilled_time_entries__c = source.total_unbilled_time_entries__c,
        total_payments_received__c = source.total_payments_received__c,
        total_expenses__c = source.total_expenses__c,
        total_billed_expenses__c = source.total_billed_expenses__c,
        total_time_entries__c = source.total_time_entries__c,
        total_billed_time_entries__c = source.total_billed_time_entries__c,
        total_payments_due__c = source.total_payments_due__c,
        total_uninvoiced_amount__c = source.total_uninvoiced_amount__c,
        payment__c = source.payment__c,
        payments_criteria_2months__c = source.payments_criteria_2months__c,
        promotion__c = source.promotion__c,
        is_synced__c = source.is_synced__c,
        email__c = source.email__c,
        case_on_hold_reasons__c = source.case_on_hold_reasons__c,
        financial_hardship__c = source.financial_hardship__c,
        case_type_name__c = source.case_type_name__c,
        doc_categories_and_subcaregories__c = source.doc_categories_and_subcaregories__c,
        successful_calls__c = source.successful_calls__c,
        live_saved__c = source.live_saved__c,
        case_count__c = source.case_count__c,
        urgency_checks__c = source.urgency_checks__c,
        urgent__c = source.urgent__c,
        previous_case_stage__c = source.previous_case_stage__c,
        consent_form_signed_by_client_in_favor__c = source.consent_form_signed_by_client_in_favor__c,
        identification_pin_code_for_individual__c = source.identification_pin_code_for_individual__c,
        client_s_identification_pin_code__c = source.client_s_identification_pin_code__c,
        not_financial_user__c = source.not_financial_user__c,
        rfe_deadline__c = source.rfe_deadline__c,
        legacy_case_stage__c = source.legacy_case_stage__c,
        filling_fees_paid__c = source.filling_fees_paid__c,
        override_tab_title__c = source.override_tab_title__c,
        approval_status__c = source.approval_status__c,
        attorney_or_paralegal__c = source.attorney_or_paralegal__c,
        emergency_deadline_date__c = source.emergency_deadline_date__c,
        total_filing_fee__c = source.total_filing_fee__c,
        total_overdue_amount__c = source.total_overdue_amount__c,
        is_cl_specialist__c = source.is_cl_specialist__c,
        approved_denied_date__c = source.approved_denied_date__c,
        count_role_records__c = source.count_role_records__c,
        live_associated__c = source.live_associated__c,
        client_name__c = source.client_name__c,
        country_of_origin__c = source.country_of_origin__c,
        psych_eval_date__c = source.psych_eval_date__c,
        scheduled_amount__c = source.scheduled_amount__c,
        no_of_days__c = source.no_of_days__c,
        submitted_to_uscis__c = source.submitted_to_uscis__c,
        turnaround_time__c = source.turnaround_time__c,
        automatic_form_errors__c = source.automatic_form_errors__c,
        lives_saved__c = source.lives_saved__c,
        reviewed_with_cl__c = source.reviewed_with_cl__c,
        ff_paid_on__c = source.ff_paid_on__c,
        receipt_notices_received__c = source.receipt_notices_received__c,
        fingerprint_appointment__c = source.fingerprint_appointment__c,
        psych_eval_completed__c = source.psych_eval_completed__c,
        psych_eval_submitted_to_uscis__c = source.psych_eval_submitted_to_uscis__c,
        rfe_submission__c = source.rfe_submission__c,
        received_prima_facie__c = source.received_prima_facie__c,
        received_work_permit__c = source.received_work_permit__c,
        consult_notes__c = source.consult_notes__c,
        not_subbmitted_documents__c = source.not_subbmitted_documents__c,
        states_of_mexico__c = source.states_of_mexico__c,
        checkboxdate__c = source.checkboxdate__c,
        checkboxf__c = source.checkboxf__c,
        client_address__c = source.client_address__c,
        foia_request__c = source.foia_request__c,
        fbi_submission__c = source.fbi_submission__c,
        appeal_deadline__c = source.appeal_deadline__c,
        approval_received__c = source.approval_received__c,
        denial_received__c = source.denial_received__c,
        client_notified__c = source.client_notified__c,
        uscis_receipt_cl_notified__c = source.uscis_receipt_cl_notified__c,
        fingerprint_cl_notified__c = source.fingerprint_cl_notified__c,
        rfe_received_cl_notified__c = source.rfe_received_cl_notified__c,
        work_permit_cl_notified__c = source.work_permit_cl_notified__c,
        approval_received_cl_notified__c = source.approval_received_cl_notified__c,
        denial_received_cl_notified__c = source.denial_received_cl_notified__c,
        received_work_permit2__c = source.received_work_permit2__c,
        work_permit_cl_notified2__c = source.work_permit_cl_notified2__c,
        urgentoverdue__c = source.urgentoverdue__c,
        priority__c = source.priority__c,
        case_submitted__c = source.case_submitted__c,
        docs_collected__c = source.docs_collected__c,
        accurint_report_completed__c = source.accurint_report_completed__c,
        attorney_notes__c = source.attorney_notes__c,
        pif__c = source.pif__c,
        overdue_amount_banner__c = source.overdue_amount_banner__c,
        case_oh_hold_template_formula__c = source.case_oh_hold_template_formula__c,
        tracking_number__c = source.tracking_number__c,
        foia_eoir__c = source.foia_eoir__c,
        sign_up_day__c = source.sign_up_day__c,
        cl_interview__c = source.cl_interview__c,
        filled_fee_is_filled_automation__c = source.filled_fee_is_filled_automation__c,
        case_delivered__c = source.case_delivered__c,
        delivered_on__c = source.delivered_on__c,
        physical_presence__c = source.physical_presence__c,
        human_trafficking__c = source.human_trafficking__c,
        vawa__c = source.vawa__c,
        credibility__c = source.credibility__c,
        extreme_hardship__c = source.extreme_hardship__c,
        law_enforcement_cooperation__c = source.law_enforcement_cooperation__c,
        inadmissibility__c = source.inadmissibility__c,
        intreview_completed__c = source.intreview_completed__c,
        forms_completed__c = source.forms_completed__c,
        attorney_approval__c = source.attorney_approval__c,
        consent_for_mts__c = source.consent_for_mts__c,
        official_records__c = source.official_records__c,
        rejection_received__c = source.rejection_received__c,
        refiling_date__c = source.refiling_date__c,
        prima_facie_cl_notified__c = source.prima_facie_cl_notified__c,
        fbi_results__c = source.fbi_results__c,
        early_aos_request__c = source.early_aos_request__c,
        mtt__c = source.mtt__c,
        early_aos_requested__c = source.early_aos_requested__c,
        early_aos_requested_cl_notified__c = source.early_aos_requested_cl_notified__c,
        early_aos_approved_cl_notified__c = source.early_aos_approved_cl_notified__c,
        aos_approval_received__c = source.aos_approval_received__c,
        referred_out_for_pe__c = source.referred_out_for_pe__c,
        pro_bono__c = source.pro_bono__c,
        latest_case_update__c = source.latest_case_update__c,
        marked_for_rfe_tagging__c = source.marked_for_rfe_tagging__c,
        rfe_delivery__c = source.rfe_delivery__c,
        rfe_tracking_number__c = source.rfe_tracking_number__c,
        ff_confirmed__c = source.ff_confirmed__c,
        check_number__c = source.check_number__c,
        submission_qc__c = source.submission_qc__c,
        qc_issues__c = source.qc_issues__c,
        qc_completed__c = source.qc_completed__c,
        follow_up_date__c = source.follow_up_date__c,
        pending_status__c = source.pending_status__c,
        refund_details__c = source.refund_details__c,
        date_ff_paid_on__c = source.date_ff_paid_on__c,
        official_records_notes__c = source.official_records_notes__c,
        removal__c = source.removal__c,
        noid_received__c = source.noid_received__c,
        noid_responded__c = source.noid_responded__c,
        service_id__c = source.service_id__c,
        original_docs_at_the_office__c = source.original_docs_at_the_office__c,
        i_765_filled__c = source.i_765_filled__c,
        cl_detained__c = source.cl_detained__c,
        simple_issues__c = source.simple_issues__c,
        supervisor_call__c = source.supervisor_call__c,
        latest_docs_fu__c = source.latest_docs_fu__c,
        supervisor_call_resolved__c = source.supervisor_call_resolved__c,
        reason_for_escalation__c = source.reason_for_escalation__c,
        case_issues__c = source.case_issues__c,
        flagged_for_issues__c = source.flagged_for_issues__c,
        template_needed__c = source.template_needed__c,
        cases_sold_with__c = source.cases_sold_with__c,
        money_back_guarantee__c = source.money_back_guarantee__c,
        i_485_interview_360__c = source.i_485_interview_360__c,
        i_485_interview_aos__c = source.i_485_interview_aos__c,
        archived__c = source.archived__c,
        unresponsive_client__c = source.unresponsive_client__c,
        sensitive_case__c = source.sensitive_case__c,
        criminal_offense__c = source.criminal_offense__c,
        case_manager_notes__c = source.case_manager_notes__c,
        asc_appointment_date__c = source.asc_appointment_date__c,
        welcome_email_sent__c = source.welcome_email_sent__c,
        reason_for_flagged_issues__c = source.reason_for_flagged_issues__c,
        last_auto_txt_communication__c = source.last_auto_txt_communication__c,
        monitor_delivery__c = source.monitor_delivery__c,
        delivery_note__c = source.delivery_note__c,
        pif2__c = source.pif2__c,
        foia_notes__c = source.foia_notes__c,
        qc_history_notes__c = source.qc_history_notes__c,
        bonafide_received__c = source.bonafide_received__c,
        licenciado__c = source.licenciado__c,
        foia_note__c = source.foia_note__c,
        reasons_for_attorney_guidance__c = source.reasons_for_attorney_guidance__c,
        status_changed_date_time__c = source.status_changed_date_time__c,
        post_dec_forms_review_edits__c = source.post_dec_forms_review_edits__c,
        issues_identified_d_f__c = source.issues_identified_d_f__c,
        follow_up_reason__c = source.follow_up_reason__c,
        attorney_call_needed__c = source.attorney_call_needed__c,
        reason_for_attorney_call__c = source.reason_for_attorney_call__c,
        supervisor_call_resolved2__c = source.supervisor_call_resolved2__c,
        dec_forms_reviewer_note__c = source.dec_forms_reviewer_note__c,
        case_monitoring__c = source.case_monitoring__c,
        case_monitoring_reason__c = source.case_monitoring_reason__c,
        concern_raised__c = source.concern_raised__c,
        concern_resolved__c = source.concern_resolved__c,
        dec_forms_sent_for_review__c = source.dec_forms_sent_for_review__c,
        emergency_check_notes__c = source.emergency_check_notes__c,
        open_warrant__c = source.open_warrant__c,
        i_131__c = source.i_131__c,
        claim_issue_found__c = source.claim_issue_found__c,
        stage__c = source.stage__c,
        bonafide_result__c = source.bonafide_result__c,
        signature__c = source.signature__c,
        relief_type__c = source.relief_type__c,
        full_translation__c = source.full_translation__c,
        form_update__c = source.form_update__c,
        id = source.id

    WHEN NOT MATCHED THEN INSERT (
     
        ownerid, 
        isdeleted, 
        name, 
        recordtypeid, 
        createddate, 
        createdbyid, 
        lastmodifieddate, 
        lastmodifiedbyid, 
        systemmodstamp, 
        lastactivitydate, 
        litify_pm__billable_matter__c, 
        litify_pm__billing_type__c, 
        litify_pm__case_type__c, 
        litify_pm__client__c, 
        litify_pm__closed_reason_details__c, 
        litify_pm__closed_reason__c, 
        litify_pm__description__c, 
        litify_pm__display_name__c, 
        litify_pm__ignore_default_plan__c, 
        litify_pm__limitations_date_satisfied__c, 
        litify_pm__matter_address_1__c, 
        litify_pm__matter_address_2__c, 
        litify_pm__matter_city__c, 
        litify_pm__matter_has_budget__c, 
        litify_pm__matter_location__c, 
        litify_pm__matter_plan__c, 
        litify_pm__matter_postal_code__c, 
        litify_pm__matter_stage_activity_formula__c, 
        litify_pm__matter_stage_activity__c, 
        litify_pm__matter_state__c, 
        litify_pm__matter__c, 
        litify_pm__open_date__c, 
        litify_pm__originating_attorney__c, 
        litify_pm__primary_intake__c, 
        litify_pm__principal_attorney__c, 
        litify_pm__source_type__c, 
        litify_pm__source__c, 
        litify_pm__status__c, 
        litify_pm__total_amount_billable__c, 
        litify_pm__total_amount_due__c, 
        litify_pm__total_matter_value__c, 
        litify_pm__total_matter_cost__c, 
        litify_pm__use_same_client_location__c, 
        litify_pm__total_amount_paid__c, 
        litify_pm__total_amount_billed__c, 
        litify_pm__total_amount_expensed_due__c, 
        litify_pm__total_amount_expensed__c, 
        litify_pm__total_amount_retained__c, 
        litify_pm__total_amount_time_entries_billed__c, 
        litify_pm__total_amount_time_entries_due__c, 
        litify_pm__total_amount_time_entries_unpaid__c, 
        litify_pm__total_amount_unbilled_expenses__c, 
        litify_pm__total_hours__c, 
        litify_pm__total_amount_time_entries__c, 
        litify_pm__last_called_at__c, 
        litify_pm__last_emailed_at__c,
        litify_pm__total_calls__c,
        litify_pm__total_emails__c,
        litify_pm__closed_date__c,
        litify_pm__default_matter_team__c,
        litify_pm__matter_team_modified__c,
        litify_pm__filed_date__c,
        litify_pm__total_damages__c,
        litify_pm__lit_matter_county__c,
        litify_pm__lit_lien_total_currency__c,
        internal_law_firm__c,
        litify_pm__manual_statute_of_limitations__c,
        litify_pm__lit_display_name_link__c,
        case_type__c,
        litify_pm__lit_total_client_payout__c,
        litify_pm__lit_damage_total__c,
        litify_pm__lit_expense_total__c,
        litify_pm__lit_lien_total__c,
        cm_case_sub_type__c,
        run_triggers__c,
        litify_ext__isteammember__c,
        litify_ext__mtm_ids__c,
        litify_ext__private__c,
        isdeceased__c,
        open_date_text__c,
        serious_injury__c,
        isminor__c,
        conflict_check__c,
        conflict_check_notes__c,
        office__c,
        billing_contact__c,
        payment_overdue__c,
        case_updates__c,
        client_info__c,
        case_number__c,
        legacy_id__c,
        data_migration_job_id__c,
        total_billable_expenses__c,
        total_unbilled_expenses__c,
        total_billable_te__c,
        total_unbilled_time_entries__c,
        total_payments_received__c,
        total_expenses__c,
        total_billed_expenses__c,
        total_time_entries__c,
        total_billed_time_entries__c,
        total_payments_due__c,
        total_uninvoiced_amount__c,
        payment__c,
        payments_criteria_2months__c,
        promotion__c,
        is_synced__c,
        email__c,
        case_on_hold_reasons__c,
        financial_hardship__c,
        case_type_name__c,
        doc_categories_and_subcaregories__c,
        successful_calls__c,
        live_saved__c,
        case_count__c,
        urgency_checks__c,
        urgent__c,
        previous_case_stage__c,
        consent_form_signed_by_client_in_favor__c,
        identification_pin_code_for_individual__c,
        client_s_identification_pin_code__c,
        not_financial_user__c,
        rfe_deadline__c,
        legacy_case_stage__c,
        filling_fees_paid__c,
        override_tab_title__c,
        approval_status__c,
        attorney_or_paralegal__c,
        emergency_deadline_date__c,
        total_filing_fee__c,
        total_overdue_amount__c,
        is_cl_specialist__c,
        approved_denied_date__c,
        count_role_records__c,
        live_associated__c,
        client_name__c,
        country_of_origin__c,
        scheduled_amount__c,
        no_of_days__c,
        submitted_to_uscis__c,
        turnaround_time__c,
        automatic_form_errors__c,
        lives_saved__c,
        reviewed_with_cl__c,
        ff_paid_on__c,
        receipt_notices_received__c,
        fingerprint_appointment__c,
        psych_eval_completed__c,
        psych_eval_submitted_to_uscis__c,
        rfe_submission__c,
        received_prima_facie__c,
        received_work_permit__c,
        consult_notes__c,
        not_subbmitted_documents__c,
        states_of_mexico__c,
        checkboxdate__c,
        checkboxf__c,
        client_address__c,
        foia_request__c,
        fbi_submission__c,
        appeal_deadline__c,
        approval_received__c,
        denial_received__c,
        client_notified__c,
        uscis_receipt_cl_notified__c,
        fingerprint_cl_notified__c,
        rfe_received_cl_notified__c,
        work_permit_cl_notified__c,
        approval_received_cl_notified__c,
        denial_received_cl_notified__c,
        received_work_permit2__c,
        work_permit_cl_notified2__c,
        urgentoverdue__c,
        priority__c,
        case_submitted__c,
        docs_collected__c,
        accurint_report_completed__c,
        attorney_notes__c,
        pif__c,
        overdue_amount_banner__c,
        case_oh_hold_template_formula__c,
        tracking_number__c,
        foia_eoir__c,
        sign_up_day__c,
        cl_interview__c,
        filled_fee_is_filled_automation__c,
        case_delivered__c,
        delivered_on__c,
        physical_presence__c,
        human_trafficking__c,
        vawa__c,
        credibility__c,
        extreme_hardship__c,
        law_enforcement_cooperation__c,
        inadmissibility__c,
        intreview_completed__c,
        forms_completed__c,
        attorney_approval__c,
        consent_for_mts__c,
        official_records__c,
        rejection_received__c,
        refiling_date__c,
        prima_facie_cl_notified__c,
        fbi_results__c,
        early_aos_request__c,
        mtt__c,
        early_aos_requested__c,
        early_aos_requested_cl_notified__c,
        early_aos_approved_cl_notified__c,
        aos_approval_received__c,
        referred_out_for_pe__c,
        pro_bono__c,
        latest_case_update__c,
        marked_for_rfe_tagging__c,
        rfe_delivery__c,
        rfe_tracking_number__c,
        ff_confirmed__c,
        check_number__c,
        submission_qc__c,
        qc_issues__c,
        qc_completed__c,
        follow_up_date__c,
        pending_status__c,
        refund_details__c,
        date_ff_paid_on__c,
        official_records_notes__c,
        removal__c,
        noid_received__c,
        noid_responded__c,
        service_id__c,
        original_docs_at_the_office__c,
        i_765_filled__c,
        cl_detained__c,
        simple_issues__c,
        supervisor_call__c,
        latest_docs_fu__c,
        supervisor_call_resolved__c,
        reason_for_escalation__c,
        case_issues__c,
        flagged_for_issues__c,
        template_needed__c,
        cases_sold_with__c,
        money_back_guarantee__c,
        i_485_interview_360__c,
        i_485_interview_aos__c,
        archived__c,
        unresponsive_client__c,
        sensitive_case__c,
        criminal_offense__c,
        case_manager_notes__c,
        asc_appointment_date__c,
        welcome_email_sent__c,
        reason_for_flagged_issues__c,
        last_auto_txt_communication__c,
        monitor_delivery__c,
        delivery_note__c,
        pif2__c,
        foia_notes__c,
        qc_history_notes__c,
        bonafide_received__c,
        licenciado__c,
        foia_note__c,
        reasons_for_attorney_guidance__c,
        status_changed_date_time__c,
        post_dec_forms_review_edits__c,
        issues_identified_d_f__c,
        follow_up_reason__c,
        attorney_call_needed__c,
        reason_for_attorney_call__c,
        supervisor_call_resolved2__c,
        dec_forms_reviewer_note__c,
        case_monitoring__c,
        case_monitoring_reason__c,
        concern_raised__c,
        concern_resolved__c,
        dec_forms_sent_for_review__c,
        emergency_check_notes__c,
        open_warrant__c,
        i_131__c,
        claim_issue_found__c,
        stage__c,
        bonafide_result__c,
        signature__c,
        relief_type__c,
        full_translation__c,
        form_update__c,
        id 

    ) VALUES (
source.ownerid,
source.isdeleted,
source.name,
source.recordtypeid,
source.createddate,
source.createdbyid,
source.lastmodifieddate,
source.lastmodifiedbyid,
source.systemmodstamp,
source.lastactivitydate,
source.litify_pm__billable_matter__c,
source.litify_pm__billing_type__c,
source.litify_pm__case_type__c,
source.litify_pm__client__c,
source.litify_pm__closed_reason_details__c,
source.litify_pm__closed_reason__c,
source.litify_pm__description__c,
source.litify_pm__display_name__c,
source.litify_pm__ignore_default_plan__c,
source.litify_pm__limitations_date_satisfied__c,
source.litify_pm__matter_address_1__c,
source.litify_pm__matter_address_2__c,
source.litify_pm__matter_city__c,
source.litify_pm__matter_has_budget__c,
source.litify_pm__matter_location__c,
source.litify_pm__matter_plan__c,
source.litify_pm__matter_postal_code__c,
source.litify_pm__matter_stage_activity_formula__c,
source.litify_pm__matter_stage_activity__c,
source.litify_pm__matter_state__c,
source.litify_pm__matter__c,
source.litify_pm__open_date__c,
source.litify_pm__originating_attorney__c,
source.litify_pm__primary_intake__c,
source.litify_pm__principal_attorney__c,
source.litify_pm__source_type__c,
source.litify_pm__source__c,
source.litify_pm__status__c,
source.litify_pm__total_amount_billable__c,
source.litify_pm__total_amount_due__c,
source.litify_pm__total_matter_value__c,
source.litify_pm__total_matter_cost__c,
source.litify_pm__use_same_client_location__c,
source.litify_pm__total_amount_paid__c,
source.litify_pm__total_amount_billed__c,
source.litify_pm__total_amount_expensed_due__c,
source.litify_pm__total_amount_expensed__c,
source.litify_pm__total_amount_retained__c,
source.litify_pm__total_amount_time_entries_billed__c,
source.litify_pm__total_amount_time_entries_due__c,
source.litify_pm__total_amount_time_entries_unpaid__c,
source.litify_pm__total_amount_unbilled_expenses__c,
source.litify_pm__total_hours__c,
source.litify_pm__total_amount_time_entries__c,
source.litify_pm__last_called_at__c,
source.litify_pm__last_emailed_at__c,
source.litify_pm__total_calls__c,
source.litify_pm__total_emails__c,
source.litify_pm__closed_date__c,
source.litify_pm__default_matter_team__c,
source.litify_pm__matter_team_modified__c,
source.litify_pm__filed_date__c,
source.litify_pm__total_damages__c,
source.litify_pm__lit_matter_county__c,
source.litify_pm__lit_lien_total_currency__c,
source.internal_law_firm__c,
source.litify_pm__manual_statute_of_limitations__c,
source.litify_pm__lit_display_name_link__c,
source.case_type__c,
source.litify_pm__lit_total_client_payout__c,
source.litify_pm__lit_damage_total__c,
source.litify_pm__lit_expense_total__c,
source.litify_pm__lit_lien_total__c,
source.cm_case_sub_type__c,
source.run_triggers__c,
source.litify_ext__isteammember__c,
source.litify_ext__mtm_ids__c,
source.litify_ext__private__c,
source.isdeceased__c,
source.open_date_text__c,
source.serious_injury__c,
source.isminor__c,
source.conflict_check__c,
source.conflict_check_notes__c,
source.office__c,
source.billing_contact__c,
source.payment_overdue__c,
source.case_updates__c,
source.client_info__c,
source.case_number__c,
source.legacy_id__c,
source.data_migration_job_id__c,
source.total_billable_expenses__c,
source.total_unbilled_expenses__c,
source.total_billable_te__c,
source.total_unbilled_time_entries__c,
source.total_payments_received__c,
source.total_expenses__c,
source.total_billed_expenses__c,
source.total_time_entries__c,
source.total_billed_time_entries__c,
source.total_payments_due__c,
source.total_uninvoiced_amount__c,
source.payment__c,
source.payments_criteria_2months__c,
source.promotion__c,
source.is_synced__c,
source.email__c,
source.case_on_hold_reasons__c,
source.financial_hardship__c,
source.case_type_name__c,
source.doc_categories_and_subcaregories__c,
source.successful_calls__c,
source.live_saved__c,
source.case_count__c,
source.urgency_checks__c,
source.urgent__c,
source.previous_case_stage__c,
source.consent_form_signed_by_client_in_favor__c,
source.identification_pin_code_for_individual__c,
source.client_s_identification_pin_code__c,
source.not_financial_user__c,
source.rfe_deadline__c,
source.legacy_case_stage__c,
source.filling_fees_paid__c,
source.override_tab_title__c,
source.approval_status__c,
source.attorney_or_paralegal__c,
source.emergency_deadline_date__c,
source.total_filing_fee__c,
source.total_overdue_amount__c,
source.is_cl_specialist__c,
source.approved_denied_date__c,
source.count_role_records__c,
source.live_associated__c,
source.client_name__c,
source.country_of_origin__c,
source.scheduled_amount__c,
source.no_of_days__c,
source.submitted_to_uscis__c,
source.turnaround_time__c,
source.automatic_form_errors__c,
source.lives_saved__c,
source.reviewed_with_cl__c,
source.ff_paid_on__c,
source.receipt_notices_received__c,
source.fingerprint_appointment__c,
source.psych_eval_completed__c,
source.psych_eval_submitted_to_uscis__c,
source.rfe_submission__c,
source.received_prima_facie__c,
source.received_work_permit__c,
source.consult_notes__c,
source.not_subbmitted_documents__c,
source.states_of_mexico__c,
source.checkboxdate__c,
source.checkboxf__c,
source.client_address__c,
source.foia_request__c,
source.fbi_submission__c,
source.appeal_deadline__c,
source.approval_received__c,
source.denial_received__c,
source.client_notified__c,
source.uscis_receipt_cl_notified__c,
source.fingerprint_cl_notified__c,
source.rfe_received_cl_notified__c,
source.work_permit_cl_notified__c,
source.approval_received_cl_notified__c,
source.denial_received_cl_notified__c,
source.received_work_permit2__c,
source.work_permit_cl_notified2__c,
source.urgentoverdue__c,
source.priority__c,
source.case_submitted__c,
source.docs_collected__c,
source.accurint_report_completed__c,
source.attorney_notes__c,
source.pif__c,
source.overdue_amount_banner__c,
source.case_oh_hold_template_formula__c,
source.tracking_number__c,
source.foia_eoir__c,
source.sign_up_day__c,
source.cl_interview__c,
source.filled_fee_is_filled_automation__c,
source.case_delivered__c,
source.delivered_on__c,
source.physical_presence__c,
source.human_trafficking__c,
source.vawa__c,
source.credibility__c,
source.extreme_hardship__c,
source.law_enforcement_cooperation__c,
source.inadmissibility__c,
source.intreview_completed__c,
source.forms_completed__c,
source.attorney_approval__c,
source.consent_for_mts__c,
source.official_records__c,
source.rejection_received__c,
source.refiling_date__c,
source.prima_facie_cl_notified__c,
source.fbi_results__c,
source.early_aos_request__c,
source.mtt__c,
source.early_aos_requested__c,
source.early_aos_requested_cl_notified__c,
source.early_aos_approved_cl_notified__c,
source.aos_approval_received__c,
source.referred_out_for_pe__c,
source.pro_bono__c,
source.latest_case_update__c,
source.marked_for_rfe_tagging__c,
source.rfe_delivery__c,
source.rfe_tracking_number__c,
source.ff_confirmed__c,
source.check_number__c,
source.submission_qc__c,
source.qc_issues__c,
source.qc_completed__c,
source.follow_up_date__c,
source.pending_status__c,
source.refund_details__c,
source.date_ff_paid_on__c,
source.official_records_notes__c,
source.removal__c,
source.noid_received__c,
source.noid_responded__c,
source.service_id__c,
source.original_docs_at_the_office__c,
source.i_765_filled__c,
source.cl_detained__c,
source.simple_issues__c,
source.supervisor_call__c,
source.latest_docs_fu__c,
source.supervisor_call_resolved__c,
source.reason_for_escalation__c,
source.case_issues__c,
source.flagged_for_issues__c,
source.template_needed__c,
source.cases_sold_with__c,
source.money_back_guarantee__c,
source.i_485_interview_360__c,
source.i_485_interview_aos__c,
source.archived__c,
source.unresponsive_client__c,
source.sensitive_case__c,
source.criminal_offense__c,
source.case_manager_notes__c,
source.asc_appointment_date__c,
source.welcome_email_sent__c,
source.reason_for_flagged_issues__c,
source.last_auto_txt_communication__c,
source.monitor_delivery__c,
source.delivery_note__c,
source.pif2__c,
source.foia_notes__c,
source.qc_history_notes__c,
source.bonafide_received__c,
source.licenciado__c,
source.foia_note__c,
source.reasons_for_attorney_guidance__c,
source.status_changed_date_time__c,
source.post_dec_forms_review_edits__c,
source.issues_identified_d_f__c,
source.follow_up_reason__c,
source.attorney_call_needed__c,
source.reason_for_attorney_call__c,
source.supervisor_call_resolved2__c,
source.dec_forms_reviewer_note__c,
source.case_monitoring__c,
source.case_monitoring_reason__c,
source.concern_raised__c,
source.concern_resolved__c,
source.dec_forms_sent_for_review__c,
source.emergency_check_notes__c,
source.open_warrant__c,
source.i_131__c,
source.claim_issue_found__c,
source.stage__c,
source.bonafide_result__c,
source.signature__c,
source.relief_type__c,
source.full_translation__c,
source.form_update__c,
source.id

    );

    DROP TABLE temp_source_m;
    DELETE FROM litify.matter_staging;

END;
$$